services:
    postgres:
        image: pgvector/pgvector:pg17
        container_name: postgres_ia
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
            POSTGRES_DB: ${POSTGRES_DB:-pergunteme_juri}
        volumes:
            - pergunteme_juri:/var/lib/postgresql/data

volumes:
    pergunteme_juri:
